<?php

namespace Versionable\Ration\Command\Exception;

require_once dirname(__FILE__) . '/../../../../../../src/Versionable/Ration/Command/Exception/PipelineException.php';

/**
 * Test class for PipelineException.
 * Generated by PHPUnit on 2012-07-23 at 16:59:06.
 */
class PipelineExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PipelineException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PipelineException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}

?>
