<?php

namespace Versionable\Ration\Response\Exception;

require_once dirname(__FILE__) . '/../../../../../../src/Versionable/Ration/Response/Exception/InvalidResponseException.php';

/**
 * Test class for InvalidResponseException.
 * Generated by PHPUnit on 2012-07-23 at 16:59:37.
 */
class InvalidResponseExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InvalidResponseException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new InvalidResponseException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}

?>
