<?php

namespace Versionable\Ration\Command;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Ration/Command/Multi.php';

/**
 * Test class for Multi.
 * Generated by PHPUnit on 2012-07-23 at 16:59:06.
 */
class MultiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Multi
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Multi;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Command\Multi::getCommand
     * @todo Implement testGetCommand().
     */
    public function testGetCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\Multi::getParameters
     * @todo Implement testGetParameters().
     */
    public function testGetParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
