<?php

namespace Versionable\Ration\Command;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Ration/Command/SelectCommand.php';

/**
 * Test class for SelectCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:30.
 */
class SelectCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SelectCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SelectCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Command\SelectCommand::getIndex
     * @todo Implement testGetIndex().
     */
    public function testGetIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\SelectCommand::setIndex
     * @todo Implement testSetIndex().
     */
    public function testSetIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\SelectCommand::getCommand
     * @todo Implement testGetCommand().
     */
    public function testGetCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\SelectCommand::getParameters
     * @todo Implement testGetParameters().
     */
    public function testGetParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
