<?php

namespace Versionable\Ration\Client;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Ration/Client/Client.php';

/**
 * Test class for Client.
 * Generated by PHPUnit on 2012-07-23 at 16:54:09.
 */
class ClientTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Client
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Client;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Client\Client::setConnection
     * @todo Implement testSetConnection().
     */
    public function testSetConnection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Client\Client::getConnection
     * @todo Implement testGetConnection().
     */
    public function testGetConnection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Client\Client::send
     * @todo Implement testSend().
     */
    public function testSend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
