<?php

namespace Versionable\Ration\Client;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Ration/Client/Queue.php';

/**
 * Test class for Queue.
 * Generated by PHPUnit on 2012-07-23 at 16:59:05.
 */
class QueueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Queue
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Queue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Client\Queue::send
     * @todo Implement testSend().
     */
    public function testSend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Client\Queue::queue
     * @todo Implement testQueue().
     */
    public function testQueue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Client\Queue::getQueue
     * @todo Implement testGetQueue().
     */
    public function testGetQueue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Client\Queue::reset
     * @todo Implement testReset().
     */
    public function testReset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Client\Queue::flush
     * @todo Implement testFlush().
     */
    public function testFlush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
