<?php

namespace Versionable\Ration\Connection\Stream;

require_once dirname(__FILE__) . '/../../../../../../src/Versionable/Ration/Connection/Stream/TCP.php';

/**
 * Test class for TCP.
 * Generated by PHPUnit on 2012-08-03 at 16:57:53.
 */
class TCPTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var TCP
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TCP;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\TCP::getHost
     * @todo Implement testGetHost().
     */
    public function testGetHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\TCP::setHost
     * @todo Implement testSetHost().
     */
    public function testSetHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\TCP::getPort
     * @todo Implement testGetPort().
     */
    public function testGetPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\TCP::setPort
     * @todo Implement testSetPort().
     */
    public function testSetPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\TCP::getAddress
     * @todo Implement testGetAddress().
     */
    public function testGetAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\TCP::isValid
     * @todo Implement testIsValid().
     */
    public function testIsValid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
