<?php

namespace Versionable\Ration\Connection\Stream;

require_once dirname(__FILE__) . '/../../../../../../src/Versionable/Ration/Connection/Stream/TCP.php';

/**
 * Test class for TCP.
 * Generated by PHPUnit on 2012-08-03 at 16:57:53.
 */
class TCPTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var TCP
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TCP;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\TCP::getHost
     */
    public function testGetHost()
    {
        $this->assertEquals('localhost', $this->object->getHost());
    }

    /**
     * @depends testGetHost
     * @covers Versionable\Ration\Connection\Stream\TCP::setHost
     * @covers Versionable\Ration\Connection\Stream\TCP::getHost
     */
    public function testSetHost()
    {
        $host = 'test';
        
        $this->object->setHost($host);
        $this->assertEquals($host, $this->object->getHost());
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\TCP::getPort
     */
    public function testGetPort()
    {
        $this->assertEquals(6379, $this->object->getPort());
    }

    /**
     * @depends testGetPort
     * @covers Versionable\Ration\Connection\Stream\TCP::setPort
     * @covers Versionable\Ration\Connection\Stream\TCP::getPort
     */
    public function testSetPort()
    {
        $port = 1337;
        
        $this->object->setPort($port);
        $this->assertEquals($port, $this->object->getPort());
    }
    
    /**
     * @covers Versionable\Ration\Connection\Stream\TCP::isValid
     */
    public function testIsValid()
    {
        $this->assertTrue($this->object->isValid());
    }

    /**
     * @depends testGetHost
     * @depends testGetPort
     * @depends testIsValid
     * @covers Versionable\Ration\Connection\Stream\TCP::getAddress
     * @covers Versionable\Ration\Connection\Stream\TCP::getHost
     * @covers Versionable\Ration\Connection\Stream\TCP::getPort
     * @covers Versionable\Ration\Connection\Stream\TCP::isValid
     * @todo Implement testGetAddress().
     */
    public function testGetAddress()
    {
        $address = 'tcp://localhost:6379';
        
        $this->assertEquals($address, $this->object->getAddress());
    }
}
