<?php

namespace Versionable\Ration\Connection\Stream;

require_once dirname(__FILE__) . '/../../../../../../src/Versionable/Ration/Connection/Stream/UnixSocket.php';

/**
 * Test class for UnixSocket.
 * Generated by PHPUnit on 2012-08-03 at 16:57:53.
 */
class UnixSocketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var UnixSocket
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UnixSocket;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\UnixSocket::getPath
     * @todo Implement testGetPath().
     */
    public function testGetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\UnixSocket::setPath
     * @todo Implement testSetPath().
     */
    public function testSetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\UnixSocket::getAddress
     * @todo Implement testGetAddress().
     */
    public function testGetAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Connection\Stream\UnixSocket::isValid
     * @todo Implement testIsValid().
     */
    public function testIsValid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
