<?php

namespace Versionable\Ration\Connection\Exception;

require_once dirname(__FILE__) . '/../../../../../../src/Versionable/Ration/Connection/Exception/ConnectionException.php';

/**
 * Test class for ConnectionException.
 * Generated by PHPUnit on 2012-07-23 at 16:54:11.
 */
class ConnectionExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ConnectionException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConnectionException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}

?>
