<?php

namespace Versionable\Ration\Response;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Ration/Response/Response.php';

/**
 * Test class for Response.
 * Generated by PHPUnit on 2012-07-23 at 16:54:10.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Response\Response::getContent
     * @todo Implement testGetContent().
     */
    public function testGetContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Response\Response::setContent
     * @todo Implement testSetContent().
     */
    public function testSetContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Response\Response::parse
     * @todo Implement testParse().
     */
    public function testParse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
