<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\AuthCommand;

/**
 * Test class for AuthCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:32.
 */
class AuthCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AuthCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AuthCommand;
    }

    /**
     * @covers Versionable\Ration\Command\AuthCommand::getPassword
     */
    public function testGetPassword()
    {
        $this->assertNull($this->object->getPassword());
    }

    /**
     * @depends testGetPassword
     * @covers Versionable\Ration\Command\AuthCommand::setPassword
     * @covers Versionable\Ration\Command\AuthCommand::getPassword
     */
    public function testSetPassword()
    {
        $password = 'test';
        
        $this->object->setPassword($password);
        $this->assertEquals($password, $this->object->getPassword());
    }

    /**
     * @covers Versionable\Ration\Command\AuthCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('auth', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\AuthCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null), $this->object->getParameters());
    }

}
