<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\DelCommand;

/**
 * Test class for DelCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:29.
 */
class DelCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DelCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DelCommand;
    }

    /**
     * @covers Versionable\Ration\Command\DelCommand::getKeys
     */
    public function testGetKeys()
    {
        $this->assertEquals(array(), $this->object->getKeys());
    }

    /**
     * @depends testGetKeys
     * @covers Versionable\Ration\Command\DelCommand::setKeys
     * @covers Versionable\Ration\Command\DelCommand::getKeys
     */
    public function testSetKeys()
    {
        $keys = array(
            'test', 'test2', 'test3'
        );
        
        $this->object->setKeys($keys);
        $this->assertEquals($keys, $this->object->getKeys());
    }

    /**
     * @depends testGetKeys
     * @covers Versionable\Ration\Command\DelCommand::addKey
     * @covers Versionable\Ration\Command\DelCommand::getKeys
     */
    public function testAddKey()
    {
        $key = 'test';
        
        $this->object->addKey($key);
        $this->assertEquals(array($key), $this->object->getKeys());
    }

    /**
     * @covers Versionable\Ration\Command\DelCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('del', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\DelCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(), $this->object->getParameters());
    }

}