<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\EchoCommand;

/**
 * Test class for EchoCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:31.
 */
class EchoCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var EchoCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EchoCommand;
    }

    /**
     * @covers Versionable\Ration\Command\EchoCommand::getMessage
     */
    public function testGetMessage()
    {
        $this->assertNull($this->object->getMessage());
    }

    /**
     * @depends testGetMessage
     * @covers Versionable\Ration\Command\EchoCommand::setMessage
     * @covers Versionable\Ration\Command\EchoCommand::getMessage
     */
    public function testSetMessage()
    {
        $message = 'test';
        
        $this->object->setMessage($message);
        $this->assertEquals($message, $this->object->getMessage());
    }

    /**
     * @covers Versionable\Ration\Command\EchoCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('echo', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\EchoCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null), $this->object->getParameters());
    }

}