<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\ExecCommand;

/**
 * Test class for ExecCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:31.
 */
class ExecCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ExecCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExecCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Command\ExecCommand::getCommand
     * @todo Implement testGetCommand().
     */
    public function testGetCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\ExecCommand::getParameters
     * @todo Implement testGetParameters().
     */
    public function testGetParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
