<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\ExistsCommand;

/**
 * Test class for ExistsCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:31.
 */
class ExistsCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ExistsCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExistsCommand;
    }

    /**
     * @covers Versionable\Ration\Command\ExistsCommand::getKey
     */
    public function testGetKey()
    {
        $this->assertNull($this->object->getKey());
    }

    /**
     * @depends testGetKey
     * @covers Versionable\Ration\Command\ExistsCommand::setKey
     * @covers Versionable\Ration\Command\ExistsCommand::getKey
     */
    public function testSetKey()
    {
        $key = 'test';
        
        $this->object->setKey($key);
        $this->assertEquals($key, $this->object->getKey());
    }

    /**
     * @covers Versionable\Ration\Command\ExistsCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('exists', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\ExistsCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null), $this->object->getParameters());
    }

}
