<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\ExpireCommand;

/**
 * Test class for ExpireCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:30.
 */
class ExpireCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ExpireCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExpireCommand;
    }

    /**
     * @covers Versionable\Ration\Command\ExpireCommand::getKey
     */
    public function testGetKey()
    {
        $this->assertNull($this->object->getKey());
    }

    /**
     * @depends testGetKey
     * @covers Versionable\Ration\Command\ExpireCommand::setKey
     * @covers Versionable\Ration\Command\ExpireCommand::getKey
     */
    public function testSetKey()
    {
        $key = 'test';
        
        $this->object->setKey($key);
        $this->assertEquals($key, $this->object->getKey());
    }

    /**
     * @covers Versionable\Ration\Command\ExpireCommand::getSeconds
     */
    public function testGetSeconds()
    {
        $this->assertEquals(0, $this->object->getSeconds());
    }

    /**
     * @depends testGetSeconds
     * @covers Versionable\Ration\Command\ExpireCommand::setSeconds
     * @covers Versionable\Ration\Command\ExpireCommand::getSeconds
     */
    public function testSetSeconds()
    {
        $seconds = 3;
        
        $this->object->setSeconds($seconds);
        $this->assertEquals($seconds, $this->object->getSeconds());
    }

    /**
     * @covers Versionable\Ration\Command\ExpireCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('expire', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\ExpireCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null, 0), $this->object->getParameters());
    }
}