<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\FlushAllCommand;

/**
 * Test class for FlushAllCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:31.
 */
class FlushAllCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var FlushAllCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FlushAllCommand;
    }

    /**
     * @covers Versionable\Ration\Command\FlushAllCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('flushall', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\FlushAllCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(), $this->object->getParameters());
    }

}