<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\GetCommand;

/**
 * Test class for GetCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:31.
 */
class GetCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var GetCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GetCommand;
    }

    /**
     * @covers Versionable\Ration\Command\GetCommand::getKey
     */
    public function testGetKey()
    {
        $this->assertNull($this->object->getKey());
    }

    /**
     * @depends testGetKey
     * @covers Versionable\Ration\Command\GetCommand::setKey
     * @covers Versionable\Ration\Command\GetCommand::getKey
     */
    public function testSetKey()
    {
        $key = 'test';
        
        $this->object->setKey($key);
        $this->assertEquals($key, $this->object->getKey());
    }

    /**
     * @covers Versionable\Ration\Command\GetCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('get', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\GetCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null), $this->object->getParameters());
    }

}