<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\InfoCommand;

/**
 * Test class for InfoCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:31.
 */
class InfoCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InfoCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new InfoCommand;
    }

    /**
     * @covers Versionable\Ration\Command\InfoCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('info', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\InfoCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(), $this->object->getParameters());
    }

}