<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\KeysCommand;

/**
 * Test class for KeysCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:31.
 */
class KeysCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var KeysCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new KeysCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Command\KeysCommand::getPattern
     */
    public function testGetPattern()
    {
        $this->assertNull($this->object->getPattern());
    }

    /**
     * @depends testGetPattern
     * @covers Versionable\Ration\Command\KeysCommand::setPattern
     * @covers Versionable\Ration\Command\KeysCommand::getPattern
     */
    public function testSetPattern()
    {
        $pattern = '[\w]+';
        
        $this->object->setPattern($pattern);
        $this->assertEquals($pattern, $this->object->getPattern());
    }

    /**
     * @covers Versionable\Ration\Command\KeysCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('keys', $this->object->getCommand());
    }

    /**
     * @depends testGetPattern
     * @covers Versionable\Ration\Command\KeysCommand::getParameters
     * @covers Versionable\Ration\Command\KeysCommand::getPattern
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null), $this->object->getParameters());
    }

}
