<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\MultiCommand;

/**
 * Test class for MultiCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:30.
 */
class MultiCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var MultiCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MultiCommand;
    }

    /**
     * @covers Versionable\Ration\Command\MultiCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('multi', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\MultiCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(), $this->object->getParameters());
    }

}
