<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\PersistCommand;

/**
 * Test class for PersistCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:32.
 */
class PersistCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PersistCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PersistCommand;
    }

    /**
     * @covers Versionable\Ration\Command\PersistCommand::getKey
     */
    public function testGetKey()
    {
        $this->assertNull($this->object->getKey());
    }

    /**
     * @depends testGetKey
     * @covers Versionable\Ration\Command\PersistCommand::setKey
     * @covers Versionable\Ration\Command\PersistCommand::getKey
     */
    public function testSetKey()
    {
        $key = 'test';
        
        $this->object->setKey($key);
        $this->assertEquals($key, $this->object->getKey());
    }

    /**
     * @covers Versionable\Ration\Command\PersistCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('persist', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\PersistCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null), $this->object->getParameters());
    }

}