<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\PingCommand;

/**
 * Test class for PingCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:29.
 */
class PingCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PingCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PingCommand;
    }

    /**
     * @covers Versionable\Ration\Command\PingCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('ping', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\PingCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(), $this->object->getParameters());
    }

}