<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\QuitCommand;

/**
 * Test class for QuitCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:29.
 */
class QuitCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var QuitCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new QuitCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Command\QuitCommand::getCommand
     * @todo Implement testGetCommand().
     */
    public function testGetCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\QuitCommand::getParameters
     * @todo Implement testGetParameters().
     */
    public function testGetParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
