<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\RenameCommand;

/**
 * Test class for RenameCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:31.
 */
class RenameCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var RenameCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RenameCommand;
    }

    /**
     * @covers Versionable\Ration\Command\RenameCommand::getKey
     */
    public function testGetKey()
    {
        $this->assertNull($this->object->getKey());
    }

    /**
     * @depends testGetKey
     * @covers Versionable\Ration\Command\RenameCommand::setKey
     * @covers Versionable\Ration\Command\RenameCommand::getKey
     */
    public function testSetKey()
    {
        $key = 'test';
        
        $this->object->setKey($key);
        $this->assertEquals($key, $this->object->getKey());
    }

    /**
     * @covers Versionable\Ration\Command\RenameCommand::getNewKey
     */
    public function testGetNewKey()
    {
        $this->assertNull($this->object->getNewKey());
    }

    /**
     * @depends testGetNewKey
     * @covers Versionable\Ration\Command\RenameCommand::setNewKey
     * @covers Versionable\Ration\Command\RenameCommand::getNewKey
     */
    public function testSetNewKey()
    {
        $key = 'test';
        
        $this->object->setNewKey($key);
        $this->assertEquals($key, $this->object->getNewKey());
    }

    /**
     * @covers Versionable\Ration\Command\RenameCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('rename', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\RenameCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null, null), $this->object->getParameters());
    }

}