<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\RestoreCommand;

/**
 * Test class for RestoreCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:30.
 */
class RestoreCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var RestoreCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RestoreCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::getKey
     * @todo Implement testGetKey().
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::setKey
     * @todo Implement testSetKey().
     */
    public function testSetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::getValue
     * @todo Implement testGetValue().
     */
    public function testGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::setValue
     * @todo Implement testSetValue().
     */
    public function testSetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::getTimeToLive
     * @todo Implement testGetTimeToLive().
     */
    public function testGetTimeToLive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::setTimeToLive
     * @todo Implement testSetTimeToLive().
     */
    public function testSetTimeToLive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::getCommand
     * @todo Implement testGetCommand().
     */
    public function testGetCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::getParameters
     * @todo Implement testGetParameters().
     */
    public function testGetParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
