<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\RestoreCommand;

/**
 * Test class for RestoreCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:30.
 */
class RestoreCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var RestoreCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RestoreCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::getKey
     */
    public function testGetKey()
    {
        $this->assertNull($this->object->getKey());
    }
    
    /**
     * @depends testGetKey
     * @covers Versionable\Ration\Command\RestoreCommand::setKey
     * @covers Versionable\Ration\Command\RestoreCommand::getKey
     */
    public function testSetKey()
    {
        $key = 'test';
        
        $this->object->setKey($key);
        $this->assertEquals($key, $this->object->getKey());
    }
    
    /**
     * @covers Versionable\Ration\Command\RestoreCommand::getValue
     */
    public function testGetValue()
    {
        $this->assertNull($this->object->getValue());
    }

    /**
     * @depends testGetValue
     * @covers Versionable\Ration\Command\RestoreCommand::setValue
     * @covers Versionable\Ration\Command\RestoreCommand::getValue
     */
    public function testSetValue()
    {
        $value = 'test';
        
        $this->object->setValue($value);
        $this->assertEquals($value, $this->object->getValue());
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::getTimeToLive
     */
    public function testGetTimeToLive()
    {
        $this->assertEquals(0, $this->object->getTimeToLive());
    }

    /**
     * @depends testGetTimeToLive
     * @covers Versionable\Ration\Command\RestoreCommand::setTimeToLive
     * @covers Versionable\Ration\Command\RestoreCommand::getTimeToLive
     */
    public function testSetTimeToLive()
    {
        $ttl = 3;
        
        $this->object->setTimeToLive($ttl);
        $this->assertEquals($ttl, $this->object->getTimeToLive());
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('restore', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\RestoreCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null, null, 0), $this->object->getParameters());
    }

}