<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\SelectCommand;

/**
 * Test class for SelectCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:30.
 */
class SelectCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SelectCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SelectCommand;
    }

    /**
     * @covers Versionable\Ration\Command\SelectCommand::getIndex
     */
    public function testGetIndex()
    {
        $this->assertNull($this->object->getIndex());
    }

    /**
     * @depends testGetIndex
     * @covers Versionable\Ration\Command\SelectCommand::setIndex
     * @covers Versionable\Ration\Command\SelectCommand::getIndex
     */
    public function testSetIndex()
    {
        $index = 2;
        
        $this->object->setIndex($index);
        $this->assertEquals($index, $this->object->getIndex());
    }

    /**
     * @covers Versionable\Ration\Command\SelectCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('select', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\SelectCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null), $this->object->getParameters());
    }

}