<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\SetCommand;

/**
 * Test class for SetCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:29.
 */
class SetCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SetCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SetCommand;
    }

    /**
     * @covers Versionable\Ration\Command\SetCommand::getKey
     */
    public function testGetKey()
    {
        $this->assertNull($this->object->getKey());
    }

    /**
     * @depends testGetKey
     * @covers Versionable\Ration\Command\SetCommand::setKey
     * @covers Versionable\Ration\Command\SetCommand::getKey
     */
    public function testSetKey()
    {
        $key = 'test';
        
        $this->object->setKey($key);
        $this->assertEquals($key, $this->object->getKey());
    }

    /**
     * @covers Versionable\Ration\Command\SetCommand::getValue
     */
    public function testGetValue()
    {
        $this->assertNull($this->object->getValue());
    }

    /**
     * @depends testGetValue
     * @covers Versionable\Ration\Command\SetCommand::setValue
     * @covers Versionable\Ration\Command\SetCommand::getValue
     */
    public function testSetValue()
    {
        $value = 'test';
        
        $this->object->setValue($value);
        $this->assertEquals($value, $this->object->getValue());
    }

    /**
     * @covers Versionable\Ration\Command\SetCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('set', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\SetCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(null, null), $this->object->getParameters());
    }

}