<?php

namespace Versionable\Ration\Command;

use Versionable\Ration\Command\TimeCommand;

/**
 * Test class for TimeCommand.
 * Generated by PHPUnit on 2012-07-23 at 17:59:30.
 */
class TimeCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var TimeCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TimeCommand;
    }

    /**
     * @covers Versionable\Ration\Command\TimeCommand::getCommand
     */
    public function testGetCommand()
    {
        $this->assertEquals('time', $this->object->getCommand());
    }

    /**
     * @covers Versionable\Ration\Command\TimeCommand::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array(), $this->object->getParameters());
    }

}